### ISSUE TITLE
Client side usage support without node polyfill 

### ISSUE THREAD

**Issue by maxcnunes** [vitaly-t/connection-string#46]
Recently Sqlectron project which uses this project in the frontend was migrated from Webpack 4 to 5. In that upgrade, Webpack does not include node polyfill automatically by default anymore, and because of that, I noticed that this module imports `os` and `util` for debugging. Wondering if we could drop those dependencies or have a different build for the frontend without that and have it specified through the package.json `browser` filed for that case https://docs.npmjs.com/cli/v7/configuring-npm/package-json#browser.

https://github.com/sqlectron/sqlectron-gui/issues/656

I can try to open a PR for that change. But, if you don't want to make any of those changes that is fine, I got it working with a few custom settings:
* https://github.com/sqlectron/sqlectron-gui/blob/main/webpack.config.js#L25-L27
* https://github.com/sqlectron/sqlectron-gui/blob/main/webpack.config.js#L41-L47

**Comment by vitaly-t** [comment]
What if you simply browserify the library, explained [here](https://github.com/vitaly-t/connection-string/wiki/Browsers)?

**Comment by vitaly-t** [comment]
@maxcnunes 

I have published `4.3.3` update, making the library require `os` and `util` modules under NodeJS only.

See if it makes the difference, an let me know ;)

**Comment by maxcnunes** [comment]
Thanks for the attempt @vitaly-t. But it still failing because webpack still parses the whole file anyway. I prepared a PR which has the solution a proposed, I tested it locally and it works fine for me https://github.com/vitaly-t/connection-string/pull/47

**Comment by vitaly-t** [comment]
Released it as v4.3.4. ;)

**Comment by vitaly-t** [comment]
All Node-related code has been retired in [v5.0.0](https://github.com/vitaly-t/connection-string/releases/tag/5.0.0).
